**Author:** [Tayyib Ul Hassan](https://github.com/tayyibgondal)

**Dated:** February 6, 2023


In [73]:
import numpy as np
import time

In [2]:
print("Hello, World!")

Hello, World!


## Initializing arrays

In [6]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)    

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [8]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]


In [10]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.79989741 0.54377674]
 [0.95020649 0.78264531]]


## Slicing and Indexing

In [11]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
print(a[:2, 1:3])

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"


[[2 3]
 [6 7]]
2
2


In [12]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


## Integer array indexing

In [22]:
a = np.array([[1, 2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]])

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

print(a[[0, 1], [1, 1]])  # Integer array indexing

print(np.array([a[0, 1], a[1, 1]]))  # Integer indexing

[1 4 5]
[1 4 5]
[2 4]
[2 4]


Trick

In [24]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print(a)

b = np.array([0, 2, 0, 1])

print(a[np.arange(4), b])

a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


## Boolean array indexing

In [29]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

bool_idx = (a > 2)

print(bool_idx)

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Dtype attribute

In [33]:
x = np.array([1, 2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int32
float64
int64


## Elementwise operations

In [34]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


## Transposing arrays

In [36]:
x = np.array([
    [1, 2],
    [3, 4]
])
print(x)
print(x.T)

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Broadcasting

In [38]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
v = np.array([1, 0, 1])
y = np.empty_like(x)
print(y)

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [42]:
# Other way to do this
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))
print(vv)

y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [43]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [49]:
# Numpy broadcasting
v = np.array([1, 2, 3])
w = np.array([4, 5])
'''
Shape of v: (3,)
Shape of w: (2,)

Shape of v after broadcasting: (3, 1)
Shape of w after broadcasting: (1, 2)

Shape of product: (3, 2)
'''
print(np.reshape(v, (3, 1)) * w)  

x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])  
'''
Shape of x: (2, 3)
Shape of v: (3,)

Shape of x after broadcasting: (2, 3)
Shape of v after broadcasting: (1, 3)

Shape of sum: (2, 3)
'''
print(x + v)

'''
Shape of x.T: (3, 2)
Shape of w: (2,)

Shape of sum: (3, 2)
Shape of sum after transpose: (2, 3)
'''
print((x.T + w).T)

'''
Shape of x: (2, 3)
Shape of w: (2,)
'''
print(x + np.reshape(w, (2, 1)))

print(x * 2)


[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


## Assessment Exercises

**6. Create a function that takes a NumPy array of shape (length,width,height) and converts it in to a vector of shape (length x width x height,1). Use the function array.reshape() for this.**

In [2]:
def change_shape(numpy_array):
    l, w, h = numpy_array.shape
    numpy_array = numpy_array.reshape(l*w*h, 1)
    return numpy_array

arr = np.array([
    [[2, 3], [3, 2]], 
    [[3, 4], [53, 32]]
])

# Testing of function
reshaped_arr = change_shape(arr)
print('Shape of input array:', arr.shape)
print('Shape of output array:', reshaped_arr.shape)

Shape of input array: (2, 2, 2)
Shape of output array: (8, 1)


**7.	Building a basic mathematical function with NumPy:**

a)	Write a function that returns the sigmoid of a real number x. Use math.exp(x) for the exponential function. Sigmoid(x)=1/(1+exp(-x)).

b)	Now create a list of 5 values and call your sigmoid function with the list as input. You will get an error because math.exp() only works when input is a real number. It does not work with vectors and matrices. Now create a new function for sigmoid but this time use np.exp() instead of math.exp(). Np.exp() works with all types of inputs including real numbers, vectors and matrices. In deep learning we mostly use matrices and vectors. This is why NumPy is more useful. Call your new function with a vector created by np.array() function.


In [30]:
import math
# Sigmoid using math.exp()
def sigmoid(x):
    try:
        return 1/(1+math.exp(-x))
    except:
        return 'Error, wrong input...'

# Testing
print(sigmoid(0))

0.5


In [31]:
input = [1, 2, 3, 4, 5]
print(sigmoid(input))

Error, wrong input...


In [32]:
# Sigmoid using np.exp()
def sigmoid_numpy(x):
    try:
        return 1/(1+np.exp(-x))
    except:
        return 'Error, wrong input...'

# Testing
print(sigmoid_numpy(0))

0.5


In [35]:
input = np.array([0, 2, 3, 4, 5])
print(sigmoid_numpy(input))

[0.5        0.88079708 0.95257413 0.98201379 0.99330715]


**8.	Implementing a function on a matrix:**

Create a function that takes a matrix as input and returns the softmax (by row) of matrix. 

In [68]:
def softmax_matrix(matrix):
    # Helper function
    def softmax_row(row):
        exponentiated_row = np.exp(row)
        denominator = np.sum(exponentiated_row)
        return np.divide(exponentiated_row, denominator)
    
    # Taking row wise softmax for each row in the matrix
    for i in range(len(matrix)):
        softmaxed_row = softmax_row(matrix[i])
        matrix[i] = softmaxed_row

    return matrix


# Testing
matrix = np.array([[5.0, 7.0, 10.0], [5.0, 7.0, 10.0], [5.0, 7.0, 10.0]])
print('input', matrix)
output = softmax_matrix(matrix)
print('output', output)


input [[ 5.  7. 10.]
 [ 5.  7. 10.]
 [ 5.  7. 10.]]
output [[0.00637746 0.04712342 0.94649912]
 [0.00637746 0.04712342 0.94649912]
 [0.00637746 0.04712342 0.94649912]]


**9.	Finding dot product using NumPy:**

d)	Create a function that implements dot product of two vectors. The input to the function should be two standard python lists. Identify the time taken to evaluate the dot product using a particular example of your choice.

e)	Now create another function that implements dot product of two vectors using np.dot() function. Identify the time taken to evaluate this dot product and compare it with the time taken in part a.


In [119]:
# Dot product of python lists
def dot_product_python(vector_a, vector_b):
    result = []
    # Iterate over each entry of vectors
    for i in range(len(vector_a)):
        result.append(vector_a[i] * vector_b[i])
    return result

# Testing of function
vector_a = [1, 2, 3]
vector_b = [4, 5, 7]
# Call function
start_time = time.perf_counter()
result = dot_product_python(vector_a, vector_b)
end_time = time.perf_counter()
# Print 
print('time taken to execute the function:', round((end_time-start_time)*1000, 4), 'ms')
print('inputs')
print('vector a:', vector_a)
print('vector b:', vector_b)
print('output')
print(result)

time taken to execute the function: 0.0493 ms
inputs
vector a: [1, 2, 3]
vector b: [4, 5, 7]
output
[4, 10, 21]


In [120]:
# Dot product of numpy arrays
def dot_product_numpy(vector_a, vector_b):
    return vector_a * vector_b

# Testing of function
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 7])
# Call function
start_time = time.perf_counter()
result = dot_product_numpy(vector_a, vector_b)
end_time = time.perf_counter()
# Print 
print('time taken to execute the function:', round((end_time-start_time)*1000, 4), 'ms')
print('inputs')
print('vector a:', vector_a)
print('vector b:', vector_b)
print('output')
print(result)

time taken to execute the function: 0.0426 ms
inputs
vector a: [1 2 3]
vector b: [4 5 7]
output
[ 4 10 21]


**10.	Finding outer product using NumPy:**

a)	Create a function that implements outer product of two vectors. The input to the function should be two standard python lists. Identify the time taken to evaluate the outer product using a particular example of your choice.

b)	Now create another function that implements outer product of two vectors using np.outer() function. Identify the time taken to evaluate this dot product and compare it with the time taken in part a.



In [125]:
# Outer product using python lists
def outer_product_python(vector_a, vector_b):
    result = []
    for i in range(len(vector_a)):
        result.append([])
        elem_a = vector_a[i]
        for elem_b in vector_b:
            result[i].append(elem_a * elem_b)
    return result


# Testing of function
vector_a = [1, 2, 3]
vector_b = [4, 5, 7]
result = outer_product_python(vector_a, vector_b)
# Print
print('inputs')
print('vector a:', vector_a)
print('vector b:', vector_b)
print('output')
print(result)


inputs
vector a: [1, 2, 3]
vector b: [4, 5, 7]
output
[[4, 5, 7], [8, 10, 14], [12, 15, 21]]


In [124]:
# Outer product using numpy vectors
def outer_product_numpy(vector_a, vector_b):
    return np.outer(vector_a, vector_b)

# Testing of function
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 7])
result = outer_product_numpy(vector_a, vector_b)
# Print
print('inputs')
print('vector a:', vector_a)
print('vector b:', vector_b)
print('output')
print(result)


inputs
vector a: [1 2 3]
vector b: [4 5 7]
output
[[ 4  5  7]
 [ 8 10 14]
 [12 15 21]]


**11.	Defining Loss Functions**

In [130]:
# L1 loss function using python list
def l1_loss_python(y, y_hat):
    loss = 0
    for i in range(len(y)):
        difference = y[i] - y_hat[i]
        difference_magnitude = abs(difference)
        loss += difference_magnitude
    
    return loss

# Testing of function
y = [1, 2, 3]
y_hat = [4, 5, 7]
loss = l1_loss_python(y, y_hat)
# Print
print('inputs')
print('y:', y)
print('y_hat:', y_hat)
print('output')
print(loss)

inputs
y: [1, 2, 3]
y_hat: [4, 5, 7]
output
10


In [127]:
# L1 loss function using numpy array
def l1_loss_numpy(y, y_hat):
    differences = y - y_hat
    differences_magnitude = np.abs(differences)
    return np.sum(differences_magnitude)

# Testing of function
y = np.array([1, 2, 3])
y_hat = np.array([4, 5, 7])
loss = l1_loss_numpy(y, y_hat)
# Print
print('inputs')
print('y:', y)
print('y_hat:', y_hat)
print('output')
print(loss)

inputs
y: [1 2 3]
y_hat: [4 5 7]
output
10


**Comparison**

In numpy implementation, I don't have to write a for loop to loop over individual elements of arrays, while in python list implementation, it has to be done by myself.

In [131]:
# L2 loss function using python list
def l2_loss_python(y, y_hat):
    loss = 0
    for i in range(len(y)):
        difference = y[i] - y_hat[i]
        difference_squared = difference * difference
        loss += difference_squared
    
    return loss

# Testing of function
y = [1, 2, 3]
y_hat = [4, 5, 7]
loss = l2_loss_python(y, y_hat)
# Print
print('inputs')
print('y:', y)
print('y_hat:', y_hat)
print('output')
print(loss)

inputs
y: [1, 2, 3]
y_hat: [4, 5, 7]
output
34


In [128]:
# L2 loss function using numpy array
def l2_loss_numpy(y, y_hat):
    differences = y - y_hat
    squared_differences = np.square(differences)
    return np.sum(squared_differences)

# Testing of function
y = np.array([1, 2, 3])
y_hat = np.array([4, 5, 7])
loss = l2_loss_numpy(y, y_hat)
# Print
print('inputs')
print('y:', y)
print('y_hat:', y_hat)
print('output')
print(loss)

inputs
y: [1 2 3]
y_hat: [4 5 7]
output
34


**Comparison**

In numpy implementation, I don't have to write a for loop to loop over individual elements of arrays, while in python list implementation, it has to be done by myself.



**12.	Perform Matrix and Matrix Addition:**

a)	Create a function that performs matrix and matrix addition by using standard python data structures only.

b)	Create a function that performs matrix and matrix addition by using NumPy arrays.


In [6]:
# Using python data structures
def add_python_matrices(matrix_a, matrix_b):
    result = []
    for row_no in range(len(matrix_a)):
        result.append([])
        for column_no in range(len(matrix_a[row_no])):
            operator_a = matrix_a[row_no][column_no]
            operator_b = matrix_b[row_no][column_no]
            result[row_no].append(operator_a + operator_b)
    
    return result

# Testing of function
matrix_a =  [[2, 3], [3, 2]]
matrix_b =  [[3, 4], [53, 32]]
result = add_python_matrices(matrix_a, matrix_b)

print('Inputs')
print('Matrix a:', matrix_a)
print('Matrix b:', matrix_b)
print('Output')
print(result)

Inputs
Matrix a: [[2, 3], [3, 2]]
Matrix b: [[3, 4], [53, 32]]
Output
[[5, 7], [56, 34]]


In [7]:
# Using numpy arrays
def add_numpy_matrices(matrix_a, matrix_b):
    return matrix_a + matrix_b

# Testing of function
matrix_a =  np.array([[2, 3], [3, 2]])
matrix_b =  np.array([[3, 4], [53, 32]])
result = add_numpy_matrices(matrix_a, matrix_b)

print('Inputs')
print('Matrix a:', matrix_a)
print('Matrix b:', matrix_b)
print('Output')
print(result)


Inputs
Matrix a: [[2 3]
 [3 2]]
Matrix b: [[ 3  4]
 [53 32]]
Output
[[ 5  7]
 [56 34]]


**13.	Perform Matrix and Vector Multiplication:**

c)	Create a function that performs matrix and vector multiplication by using standard python data structures only.

d)	Create a function that performs matrix and vector multiplication by using NumPy arrays.


In [9]:
# Using python data structures
def matrix_vector_multiplication_python(matrix, vector):
    result = []
    for row_no in range(len(matrix)):
        result.append([])
        for i in range(len(vector)):
            entry = vector[i] * matrix[row_no][i]
            result[row_no].append(entry)
    
    return result

# Testing of function
matrix = [[2, 3], [3, 2]]
vector = [3, 4]
result = matrix_vector_multiplication_python(matrix, vector)

print('Inputs')
print('Matrix:', matrix)
print('Vector:', vector)
print('Output')
print(result)


Inputs
Matrix: [[2, 3], [3, 2]]
Vector: [3, 4]
Output
[[6, 12], [9, 8]]


In [10]:
# Using numpy arrays
def matrix_vector_multiplication_numpy(matrix, vector):    
    return matrix * vector

# Testing of function
matrix = np.array([[2, 3], [3, 2]])
vector = np.array([3, 4])
result = matrix_vector_multiplication_numpy(matrix, vector)

print('Inputs')
print('Matrix:', matrix)
print('Vector:', vector)
print('Output')
print(result)


Inputs
Matrix: [[2 3]
 [3 2]]
Vector: [3 4]
Output
[[ 6 12]
 [ 9  8]]


**14.	Perform Matrix and Matrix Multiplication:**

e)	Create a function that performs matrix and matrix multiplication by using standard python data structures only.

f)	Create a function that performs matrix and matrix multiplication by using NumPy arrays.


In [22]:
# Using Python Data Structures
def matrix_multiplication_python(matrix_a, matrix_b):
    # Number of columns of first matrix should equal number of rows of the other
    assert len(matrix_a[0]) == len(matrix_b)
    result = []
    # Extract the row of first matrix
    for row_no_a in range(len(matrix_a)):
        row_a = matrix_a[row_no_a]
        result.append([])
        # For all columns of the second matrix
        for column_no_b in range(len(matrix_b[0])):
            entry_to_be_appended = 0
            pointer_row_a = 0
            # Go to each row
            for row_no_b in range(len(matrix_b)):
                row_b = matrix_b[row_no_b]
                # Go to specific column
                for i in range(len(row_b)):
                    if (i == column_no_b):
                        entry_to_be_appended += row_b[column_no_b] * row_a[pointer_row_a]
                        pointer_row_a += 1
                        break
            result[row_no_a].append(entry_to_be_appended)

    return result

# Testing of function
matrix_a = [[2, 3], [3, 2]]
matrix_b = [[1, 0], [0, 1]]

# matrix_a = [[1, 2, 3]]
# matrix_b = [[1], [1], [1]]

# matrix_a = [[1], [1], [1]]
# matrix_b = [[1, 2, 3]]

result = matrix_multiplication_python(matrix_a, matrix_b)

print('Inputs')
print('Matrix a:', matrix_a)
print('Matrix b:', matrix_b)
print('Output')
print(result)



Inputs
Matrix a: [[2, 3], [3, 2]]
Matrix b: [[1, 0], [0, 1]]
Output
[[2, 3], [3, 2]]


In [12]:
# Using numpy arrays
def matrix_multiplication_numpy(matrix_a, matrix_b):
    return matrix_a @ matrix_b

# Testing of function
matrix_a = np.array([[2, 3], [3, 2]])
matrix_b = np.array([[3, 4], [53, 32]])
result = matrix_multiplication_numpy(matrix_a, matrix_b)

print('Inputs')
print('Matrix a:', matrix_a)
print('Matrix b:', matrix_b)
print('Output')
print(result)


Inputs
Matrix a: [[2 3]
 [3 2]]
Matrix b: [[ 3  4]
 [53 32]]
Output
[[165 104]
 [115  76]]
